# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-24 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20180918_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='admin_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
