# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_admin_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='admin_level',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='country_code',
            new_name='division_id'
        ),
        migrations.RunSQL(
            '''
            INSERT INTO location_location (
              id,
              name,
              feature_type,
              division_id,
              geometry
            )
            SELECT
              ai.value AS id,
              an.value AS name,
              'relation' AS feature_type,
              ad.value AS division_id,
              ag.value AS geometry
            FROM area_area AS a
            JOIN area_areaosmid AS ai
              ON a.id = ai.object_ref_id
            JOIN area_areaname AS an
              ON a.id = an.object_ref_id
            JOIN area_areadivisionid AS ad
              ON a.id = ad.object_ref_id
            JOIN area_areageometry AS ag
              ON a.id = ag.object_ref_id
            UNION
            SELECT
              gi.value AS id,
              gn.value AS name,
              'node' AS feature_type,
              gd.value AS division_id,
              gg.value AS geometry
            FROM geosite_geosite AS g
            LEFT JOIN geosite_geositelocationid AS gi
              ON g.id = gi.object_ref_id
            LEFT JOIN geosite_geositelocationname AS gn
              ON g.id = gn.object_ref_id
            LEFT JOIN geosite_geositedivisionid AS gd
              ON g.id = gd.object_ref_id
            LEFT JOIN geosite_geositecoordinates AS gg
              ON g.id = gg.object_ref_id
            WHERE gi.value IS NOT NULL
            UNION
            SELECT
              gi.value AS id,
              gn.value AS name,
              'node' AS feature_type,
              gd.value AS division_id,
              gg.value AS geometry
            FROM geosite_geosite AS g
            LEFT JOIN geosite_geositeadminid AS gi
              ON g.id = gi.object_ref_id
            LEFT JOIN geosite_geositeadminname AS gn
              ON g.id = gn.object_ref_id
            LEFT JOIN geosite_geositedivisionid AS gd
              ON g.id = gd.object_ref_id
            LEFT JOIN geosite_geositecoordinates AS gg
              ON g.id = gg.object_ref_id
            WHERE gi.value IS NOT NULL
            UNION
            ON CONFLICT (id) DO NOTHING
            ''',
            reverse_sql='TRUNCATE location_location CASCADE'
        )
    ]
