# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_remove_location_admin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='adminlevel1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_locations', to='location.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='adminlevel2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_locations', to='location.Location'),
        ),
    ]
