# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20181113_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='adminlevel',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
