# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_location_adminlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='adminlevel',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='adminlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_locations', to='location.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='adminlevel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_locations', to='location.Location'),
        ),
    ]
