# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_location_adminlevel'),
    ]

    operations = [
        migrations.RunSQL('''
            UPDATE location_location SET
              adminlevel=s.admin_level
            FROM (
              SELECT id, admin_level
              FROM osm_data
            ) AS s
            WHERE location_location.id=s.id
        ''')
    ]
