# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-04 19:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_auto_20190209_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sfm',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
