# Generated by Django 3.1 on 2022-04-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_add_sfm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sfm',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
