# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosite', '0003_auto_20160628_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geositeadminlevel1',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='geositeadminlevel2',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='geositecoordinates',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='geositegeoname',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='geositegeonameid',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='geositename',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
    ]
