# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_auto_20160826_2057'),
        ('geosite', '0005_auto_20160810_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeositeFirstCited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', django_date_extensions.fields.ApproximateDateField(blank=True, default=None, null=True)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosite.Geosite')),
                ('sources', models.ManyToManyField(related_name='geosite_geositefirstcited_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeositeLastCited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', django_date_extensions.fields.ApproximateDateField(blank=True, default=None, null=True)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosite.Geosite')),
                ('sources', models.ManyToManyField(related_name='geosite_geositelastcited_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
