# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_auto_20160826_2057'),
        ('geosite', '0005_auto_20160810_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeositeOSMId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.IntegerField(blank=True, default=None, null=True)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosite.Geosite')),
                ('sources', models.ManyToManyField(related_name='geosite_geositeosmid_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeositeOSMName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosite.Geosite')),
                ('sources', models.ManyToManyField(related_name='geosite_geositeosmname_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='geositegeoname',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='geositegeoname',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='geositegeonameid',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='geositegeonameid',
            name='sources',
        ),
        migrations.DeleteModel(
            name='GeositeGeoname',
        ),
        migrations.DeleteModel(
            name='GeositeGeonameId',
        ),
    ]
