# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-30 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosite', '0009_auto_20161108_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geositeopenended',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='geositeopenended',
            name='sources',
        ),
        migrations.DeleteModel(
            name='GeositeOpenEnded',
        ),
    ]
