# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-30 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_auto_20160826_2057'),
        ('emplacement', '0003_auto_20160810_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplacementOpenEnded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.NullBooleanField(default=None)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplacement.Emplacement')),
                ('sources', models.ManyToManyField(related_name='emplacement_emplacementopenended_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
