# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-05 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def map_new_type(apps, schema_editor):

    EmplacementOpenEnded = apps.get_model("emplacement", "EmplacementOpenEnded")
    db_alias = schema_editor.connection.alias

    emplacements = EmplacementOpenEnded.objects.using(db_alias).all()

    for empl in emplacements:

        if empl.value == True:

            empl.new_value = 'Y'

        elif empl.value == False:

            empl.new_value = 'E'

        else:

            empl.new_value = 'N'

        empl.save()


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_auto_20160826_2057'),
        ('organization', '0009_auto_20170117_1521'),
        ('emplacement', '0004_emplacementopenended'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplacementAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplacement.Emplacement')),
                ('sources', models.ManyToManyField(related_name='emplacement_emplacementalias_related', to='source.Source')),
                ('value', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Alias')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(
            'SET CONSTRAINTS ALL IMMEDIATE',
            reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            'DROP MATERIALIZED VIEW IF EXISTS emplacement',
            reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='emplacementopenended',
            name='new_value',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('E', 'Exact')], default='N', max_length=1),
        ),
        migrations.RunPython(map_new_type),
        migrations.RemoveField(
            model_name='emplacementopenended',
            name='value',
        ),
        migrations.RenameField(
            model_name='emplacementopenended',
            old_name='new_value',
            new_name='value'
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'
        )
    ]
