# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0032_remove_source_id'),
        ('emplacement', '0007_auto_20170908_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplacementalias',
            name='accesspoints',
            field=models.ManyToManyField(related_name='emplacement_emplacementalias_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='emplacementenddate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='emplacement_emplacementenddate_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='emplacementopenended',
            name='accesspoints',
            field=models.ManyToManyField(related_name='emplacement_emplacementopenended_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='emplacementorganization',
            name='accesspoints',
            field=models.ManyToManyField(related_name='emplacement_emplacementorganization_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='emplacementrealstart',
            name='accesspoints',
            field=models.ManyToManyField(related_name='emplacement_emplacementrealstart_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='emplacementsite',
            name='accesspoints',
            field=models.ManyToManyField(related_name='emplacement_emplacementsite_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='emplacementstartdate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='emplacement_emplacementstartdate_related', to='source.AccessPoint'),
        ),
    ]
