# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplacement', '0009_auto_20180820_1923'),
    ]

    database_operations = [
        migrations.AlterField(
            model_name='emplacementalias',
            name='value',
            field=models.ForeignKey('Alias', db_constraint=False, db_index=True)
        )
    ]
    state_operations = [
        migrations.AlterField(
            model_name='emplacementalias',
            name='value',
            field=models.IntegerField(db_index=True, null=False)
        ),
        migrations.RenameField(
            model_name='emplacementalias',
            old_name='value',
            new_name='value_id'
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
