# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplacement', '0010_auto_20180820_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplacementalias',
            name='value',
            field=models.TextField(null=True)
        )
    ]
