# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-20 19:27
from __future__ import unicode_literals

import os

from django.db import migrations, connection
from django.conf import settings


def remake_view(apps, schema_editor):
    sql_folder_path = os.path.join(settings.BASE_DIR, 'sfm_pc/management/commands/sql')

    view_path = os.path.join(sql_folder_path, 'emplacement_view.sql')

    with open(view_path) as sql:
        with connection.cursor() as curs:
            curs.execute(sql.read())


class Migration(migrations.Migration):

    dependencies = [
        ('emplacement', '0011_auto_20180820_1925'),
    ]

    operations = [
        migrations.RunSQL('''
            UPDATE emplacement_emplacementalias SET
              value = s.value
            FROM (
              SELECT id, value FROM emplacement_alias
            ) AS s
            WHERE emplacement_emplacementalias.value_id = s.id
        '''),
        migrations.RunPython(remake_view)
    ]
