# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 15:38
from __future__ import unicode_literals

import os

from django.db import migrations, models, connection
import django.db.models.deletion
from django.conf import settings


def remake_views(apps, schema_editor):
    sql_folder_path = os.path.join(settings.BASE_DIR, 'sfm_pc/management/commands/sql')

    emplacement_view = os.path.join(sql_folder_path, 'emplacement_view.sql')
    emplacement_source_view = os.path.join(sql_folder_path, 'emplacement_sources_view.sql')

    with open(emplacement_view) as em, open(emplacement_source_view) as es:
        with connection.cursor() as curs:
            curs.execute(em.read())
            curs.execute(es.read())


class Migration(migrations.Migration):

    dependencies = [
        ('emplacement', '0012_auto_20180820_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alias',
        ),
        migrations.RunSQL('DROP MATERIALIZED VIEW IF EXISTS emplacement'),
        migrations.RunSQL('DROP MATERIALIZED VIEW IF EXISTS emplacement_sources'),
        migrations.AlterField(
            model_name='emplacementsite',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
        migrations.RunPython(remake_views),
    ]
