# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 15:38
from __future__ import unicode_literals

import os

from django.db import migrations, models, connection
import django.db.models.deletion
from django.conf import settings


def remake_views(apps, schema_editor):
    sql_folder_path = os.path.join(settings.BASE_DIR, 'sfm_pc/management/commands/sql')

    emplacement_view = os.path.join(sql_folder_path, 'emplacement_view.sql')
    emplacement_source_view = os.path.join(sql_folder_path, 'emplacement_sources_view.sql')

    with open(emplacement_view) as em, open(emplacement_source_view) as es:
        with connection.cursor() as curs:
            curs.execute(em.read())
            curs.execute(es.read())


class Migration(migrations.Migration):

    dependencies = [
        ('emplacement', '0012_auto_20180820_1927'),
    ]

    database_operations = [
        migrations.RunSQL('DROP MATERIALIZED VIEW IF EXISTS emplacement'),
        migrations.RunSQL('DROP MATERIALIZED VIEW IF EXISTS emplacement_sources'),
        migrations.RunSQL('ALTER TABLE emplacement_emplacementsite DROP CONSTRAINT IF EXISTS emplacement_emplacement_value_id_59e5197e_fk_geosite_geosite_id'),
        migrations.RunSQL('ALTER TABLE emplacement_emplacementsite ALTER COLUMN value_id TYPE bigint'),
        migrations.RunSQL('''
            UPDATE emplacement_emplacementsite SET
              value_id=s.value_id
            FROM (
              SELECT
                emp_site.id AS site_id,
                osm.value AS value_id
              FROM emplacement_emplacementsite AS emp_site
              JOIN geosite_geosite AS site
                ON emp_site.value_id = site.id
              JOIN geosite_geositeadminid AS osm
                ON site.id = osm.object_ref_id
              UNION
              SELECT
                emp_site.id AS site_id,
                osm.value AS value_id
              FROM emplacement_emplacementsite AS emp_site
              JOIN geosite_geosite AS site
                ON emp_site.value_id = site.id
              JOIN geosite_geositelocationid AS osm
                ON site.id = osm.object_ref_id
            ) AS s
            WHERE emplacement_emplacementsite.id = s.site_id
        '''),
        migrations.RunPython(remake_views),
    ]
    state_operations = [
        migrations.AlterField(
            model_name='emplacementsite',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alias',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=database_operations
        ),
    ]
