# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplacement', '0013_auto_20181018_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplacementalias',
            name='value_id',
        ),
        migrations.AlterField(
            model_name='emplacementalias',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
