# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-21 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emplacement', '0014_auto_20190131_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplacementTenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplacement.Emplacement')),
                ('enddate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emplacement.EmplacementEndDate')),
                ('startdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emplacement.EmplacementStartDate')),
            ],
        ),
    ]
