# Generated by Django 3.0 on 2022-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplacement', '0015_add_emplacementtenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplacementrealstart',
            name='value',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
