FROM solr:7.3

MAINTAINER Forest Gregg <fgregg@datamade.us>

RUN set -x \
&& curl -o /opt/solr/server/solr-webapp/webapp/WEB-INF/lib/jts-core-1.15.0.jar https://repo1.maven.org/maven2/org/locationtech/jts/jts-core/1.15.0/jts-core-1.15.0.jar
