version: '2.4'

services:
  solr:
    build:
      dockerfile: Dockerfile-solr-jts
      context: .
    container_name: sfm-solr
    volumes:
      - ./solr_configs:/sfm_solr_configs
      - sfm-solr-data:/opt/solr/server/solr/mycores
    command: sh -c 'solr-create -c sfm -d /sfm_solr_configs'
    ports:
      - '0.0.0.0:8983:8983'
    environment:
      - SOLR_LOG_LEVEL=ERROR
      - SOLR_HEAP=1g
    restart: on-failure

volumes:
  sfm-solr-data:
