# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_auto_20160615_1511'),
        ('organization', '0003_auto_20160623_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalias',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='organizationalias',
            name='lang',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='organizationalias',
            name='sources',
            field=models.ManyToManyField(related_name='organization_organizationalias_related', to='source.Source'),
        ),
    ]
