# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20160623_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationfoundingdate',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='organizationfoundingdate',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='organizationrealfounding',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='organizationrealfounding',
            name='sources',
        ),
        migrations.AlterField(
            model_name='organizationalias',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='organizationclassification',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='organizationname',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationFoundingDate',
        ),
        migrations.DeleteModel(
            name='OrganizationRealFounding',
        ),
    ]
