# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-17 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organizationheadquarters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationheadquarters',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='organizationheadquarters',
            name='sources',
        ),
        migrations.DeleteModel(
            name='OrganizationHeadquarters',
        ),
    ]
