# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0032_remove_source_id'),
        ('organization', '0011_organizationheadquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalias',
            name='accesspoints',
            field=models.ManyToManyField(related_name='organization_organizationalias_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='organizationclassification',
            name='accesspoints',
            field=models.ManyToManyField(related_name='organization_organizationclassification_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='organizationdivisionid',
            name='accesspoints',
            field=models.ManyToManyField(related_name='organization_organizationdivisionid_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='organizationfirstciteddate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='organization_organizationfirstciteddate_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='organizationheadquarters',
            name='accesspoints',
            field=models.ManyToManyField(related_name='organization_organizationheadquarters_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='organizationlastciteddate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='organization_organizationlastciteddate_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='organizationname',
            name='accesspoints',
            field=models.ManyToManyField(related_name='organization_organizationname_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='organizationopenended',
            name='accesspoints',
            field=models.ManyToManyField(related_name='organization_organizationopenended_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='organizationrealstart',
            name='accesspoints',
            field=models.ManyToManyField(related_name='organization_organizationrealstart_related', to='source.AccessPoint'),
        ),
    ]
