# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-20 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20180706_1721'),
    ]

    operations = [
        migrations.RunSQL('''
            DROP MATERIALIZED VIEW IF EXISTS organization
        '''),
        migrations.RunSQL('''
            DROP MATERIALIZED VIEW IF EXISTS organization_sources
        '''),
    ]
