# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20180820_2010'),
    ]

    database_operations = [
        migrations.AlterField(
            model_name='organizationalias',
            name='value',
            field=models.ForeignKey('Alias', db_constraint=False, db_index=True)
        ),
        migrations.AlterField(
            model_name='organizationclassification',
            name='value',
            field=models.ForeignKey('Classification', db_constraint=False, db_index=True)
        ),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='organizationalias',
            name='value',
            field=models.IntegerField(db_index=True, null=False)
        ),
        migrations.AlterField(
            model_name='organizationclassification',
            name='value',
            field=models.IntegerField(db_index=True, null=False)
        ),
        migrations.RenameField(
            model_name='organizationalias',
            old_name='value',
            new_name='value_id'
        ),
        migrations.RenameField(
            model_name='organizationclassification',
            old_name='value',
            new_name='value_id'
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        ),
    ]
