# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-20 20:14
from __future__ import unicode_literals

import os

from django.db import migrations, connection
from django.conf import settings


def remake_views(apps, schema_editor):
    sql_folder_path = os.path.join(settings.BASE_DIR, 'sfm_pc/management/commands/sql')
    view_paths = [
        os.path.join(sql_folder_path, 'organization_view.sql'),
        os.path.join(sql_folder_path, 'organization_sources_view.sql'),
        os.path.join(sql_folder_path, 'organization_alias_export_view.sql'),
        os.path.join(sql_folder_path, 'organization_classification_export_view.sql'),
    ]

    for view_path in view_paths:
        with open(view_path) as sql:
            with connection.cursor() as curs:
                curs.execute(sql.read())


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20180820_2013'),
    ]

    operations = [
        migrations.RunSQL('''
            UPDATE organization_organizationalias SET
              value = s.value
            FROM (
              SELECT id, value FROM organization_alias
            ) AS s
            WHERE organization_organizationalias.value_id = s.id
        '''),
        migrations.RunSQL('''
            UPDATE organization_organizationclassification SET
              value = s.value
            FROM (
              SELECT id, value FROM organization_classification
            ) AS s
            WHERE organization_organizationclassification.value_id = s.id
        '''),
        migrations.RunPython(remake_views),
        migrations.RunSQL('''
            ALTER TABLE organization_organizationalias DROP COLUMN value_id
        '''),
        migrations.RunSQL('''
            ALTER TABLE organization_organizationclassification DROP COLUMN value_id
        '''),
    ]
