# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_auto_20180820_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
