# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20181227_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alias',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.RemoveField(
            model_name='organizationalias',
            name='value_id',
        ),
        migrations.RemoveField(
            model_name='organizationclassification',
            name='value_id',
        ),
        migrations.AlterField(
            model_name='organizationalias',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationclassification',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
