# Generated by Django 3.0 on 2022-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_auto_20190131_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrealstart',
            name='value',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
