from django.urls import re_path
from django.views.decorators.cache import cache_page

from organization import views

urlpatterns = [
    re_path(r'^view/(?P<slug>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        cache_page(60 * 60 * 24)(views.OrganizationDetail.as_view()),
        name="view-organization"),
    re_path(r'name/autocomplete',
        views.organization_autocomplete,
        name="organization-autocomplete"),
    re_path(r'edit/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        views.OrganizationEditBasicsView.as_view(),
        name='edit-organization'),
    re_path(r'create/$',
        views.OrganizationCreateBasicsView.as_view(),
        name='create-organization'),
    re_path(r'delete/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        views.OrganizationDeleteView.as_view(),
        name='delete-organization'),

    re_path(r'edit/composition/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<pk>\d+)/$',
        views.OrganizationEditCompositionView.as_view(),
        name='edit-organization-composition'),
    re_path(r'create/composition/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        views.OrganizationCreateCompositionView.as_view(),
        name='create-organization-composition'),
    re_path(r'delete/composition/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<pk>\d+)/$',
        views.OrganizationDeleteCompositionView.as_view(),
        name='delete-organization-composition'),

    re_path(r'edit/membership/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<pk>\d+)/$',
        views.OrganizationEditMembershipView.as_view(),
        name='edit-organization-membership'),
    re_path(r'create/membership/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        views.OrganizationCreateMembershipView.as_view(),
        name='create-organization-membership'),
    re_path(r'delete/membership/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<pk>\d+)/$',
        views.OrganizationDeleteMembershipView.as_view(),
        name='delete-organization-membership'),

    re_path(r'edit/personnel/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<pk>\d+)/$',
        views.OrganizationEditPersonnelView.as_view(),
        name='edit-organization-personnel'),
    re_path(r'create/personnel/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        views.OrganizationCreatePersonnelView.as_view(),
        name='create-organization-personnel'),
    re_path(r'delete/personnel/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<pk>\d+)/$',
        views.OrganizationDeletePersonnelView.as_view(),
        name='delete-organization-personnel'),

    re_path(r'edit/emplacement/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<pk>\d+)/$',
        views.OrganizationEditEmplacementView.as_view(),
        name='edit-organization-emplacement'),
    re_path(r'create/emplacement/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        views.OrganizationCreateEmplacementView.as_view(),
        name='create-organization-emplacement'),
    re_path(r'delete/emplacement/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<pk>\d+)/$',
        views.OrganizationDeleteEmplacementView.as_view(),
        name='delete-organization-emplacement'),

    re_path(r'edit/association/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<pk>\d+)/$',
        views.OrganizationEditAssociationView.as_view(),
        name='edit-organization-association'),
    re_path(r'create/association/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        views.OrganizationCreateAssociationView.as_view(),
        name='create-organization-association'),
    re_path(r'delete/association/(?P<organization_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<pk>\d+)/$',
        views.OrganizationDeleteAssociationView.as_view(),
        name='delete-organization-association'),
]
