# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0031_auto_20180705_1536'),
        ('association', '0005_auto_20170905_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationarea',
            name='accesspoints',
            field=models.ManyToManyField(related_name='association_associationarea_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='associationenddate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='association_associationenddate_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='associationopenended',
            name='accesspoints',
            field=models.ManyToManyField(related_name='association_associationopenended_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='associationorganization',
            name='accesspoints',
            field=models.ManyToManyField(related_name='association_associationorganization_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='associationrealstart',
            name='accesspoints',
            field=models.ManyToManyField(related_name='association_associationrealstart_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='associationstartdate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='association_associationstartdate_related', to='source.AccessPoint'),
        ),
    ]
