# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 18:53
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations, models


def make_materialized_views(*args):
    call_command('make_materialized_views', '--recreate')


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_auto_20181018_1551'),
    ]

    operations = [
        migrations.RunSQL('''
            DROP MATERIALIZED VIEW IF EXISTS sfm_pc_areadownload
        ''', reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL('''
            DROP MATERIALIZED VIEW IF EXISTS association
        ''', reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL('''
            DROP MATERIALIZED VIEW IF EXISTS association_sources
        ''', reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL('''
            ALTER TABLE association_associationarea
            ALTER COLUMN value_id
            SET DATA TYPE BIGINT
        '''),
        migrations.RunPython(
            make_materialized_views,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
