# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-18 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_update_associationarea_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationTenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
                ('enddate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.AssociationEndDate')),
                ('startdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.AssociationStartDate')),
            ],
        ),
    ]
