# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-18 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_add_associationtenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationtenure',
            name='enddate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='association.AssociationEndDate'),
        ),
        migrations.AlterField(
            model_name='associationtenure',
            name='startdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='association.AssociationStartDate'),
        ),
    ]
