# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_auto_20161107_1946'),
        ('area', '0005_areafirstcited_arealastcited'),
    ]

    operations = [
    ]
