# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 22:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areageometry',
            name='value',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
