# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-30 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0008_auto_20161108_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areafirstcited',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='areafirstcited',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='arealastcited',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='arealastcited',
            name='sources',
        ),
        migrations.DeleteModel(
            name='AreaFirstCited',
        ),
        migrations.DeleteModel(
            name='AreaLastCited',
        ),
    ]
