# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0031_auto_20180705_1536'),
        ('area', '0009_auto_20161230_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacode',
            name='accesspoints',
            field=models.ManyToManyField(related_name='area_areacode_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='areadivisionid',
            name='accesspoints',
            field=models.ManyToManyField(related_name='area_areadivisionid_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='areageometry',
            name='accesspoints',
            field=models.ManyToManyField(related_name='area_areageometry_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='areaname',
            name='accesspoints',
            field=models.ManyToManyField(related_name='area_areaname_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='areaosmid',
            name='accesspoints',
            field=models.ManyToManyField(related_name='area_areaosmid_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='areaosmname',
            name='accesspoints',
            field=models.ManyToManyField(related_name='area_areaosmname_related', to='source.AccessPoint'),
        ),
    ]
