# Generated by Django 3.2.13 on 2022-07-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfm_pc', '0002_add_associationtenure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaDownload',
        ),
        migrations.DeleteModel(
            name='BasicDownload',
        ),
        migrations.DeleteModel(
            name='MembershipOrganizationDownload',
        ),
        migrations.DeleteModel(
            name='MembershipPersonDownload',
        ),
        migrations.DeleteModel(
            name='ParentageDownload',
        ),
        migrations.DeleteModel(
            name='SiteDownload',
        ),
        migrations.DeleteModel(
            name='SourceDownload',
        ),
    ]
