# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20160623_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondeathdate',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='persondeathdate',
            name='sources',
        ),
        migrations.AlterField(
            model_name='personalias',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personname',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='PersonDeathDate',
        ),
    ]
