# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0031_auto_20180705_1536'),
        ('person', '0006_person_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalias',
            name='accesspoints',
            field=models.ManyToManyField(related_name='person_personalias_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='persondivisionid',
            name='accesspoints',
            field=models.ManyToManyField(related_name='person_persondivisionid_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='personname',
            name='accesspoints',
            field=models.ManyToManyField(related_name='person_personname_related', to='source.AccessPoint'),
        ),
    ]
