# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-24 14:39
from __future__ import unicode_literals
import os

from django.db import migrations, models
from django.conf import settings


person_view_paths = []

forward_sql = '''
DROP MATERIALIZED VIEW IF EXISTS person;
DROP MATERIALIZED VIEW IF EXISTS person_alias_export;
DROP MATERIALIZED VIEW IF EXISTS person_title_export;
'''

sql_path = os.path.join(settings.BASE_DIR, 'sfm_pc/management/commands/sql')
files = ['person_alias_export_old.sql', 'person_sources_old.sql', 'person_old.sql']
sqls = []

for sql in files:
    with open(os.path.join(sql_path, sql)) as f:
        sqls.append(f.read())

reverse_sql = ';\n'.join(sqls)


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20180706_1825'),
    ]

    operations = [
        migrations.RunSQL(forward_sql, reverse_sql=reverse_sql),
        migrations.RunSQL(
            ['ALTER TABLE person_personalias ADD COLUMN alias_id bigint'],
            reverse_sql=['ALTER TABLE person_personalias DROP COLUMN alias_id']
        ),
        migrations.RunSQL(
            ['UPDATE person_personalias SET alias_id=value_id'],
            reverse_sql=['UPDATE person_personalias SET alias_id=NULL']
        ),
        migrations.AlterField(
            model_name='personalias',
            name='value',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
