# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-24 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20180724_1439'),
    ]

    operations = [
        migrations.RunSQL(
            ['UPDATE person_personalias SET value=s.value FROM (SELECT p.id, a.value FROM person_alias AS a JOIN person_personalias AS p ON a.id = p.alias_id) AS s WHERE person_personalias.id = s.id'],
            reverse_sql=['DELETE FROM person_personalias']
        )
    ]
