# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-24 16:10
from __future__ import unicode_literals
import os

from django.db import migrations
from django.conf import settings


sql_path = os.path.join(settings.BASE_DIR, 'sfm_pc/management/commands/sql')
files = ['person_alias_export_view.sql', 'person_sources_view.sql', 'person_view.sql']
sqls = []

for sql in files:
    with open(os.path.join(sql_path, sql)) as f:
        sqls.append(f.read())

forward_sql = ';\n'.join(sqls)


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20180724_1441'),
    ]

    operations = [
        migrations.RunSQL(forward_sql, reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(
            name='Alias',
        ),
    ]
