# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0034_auto_20180711_2034'),
        ('person', '0010_delete_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonBiography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personbiography_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('sources', models.ManyToManyField(related_name='person_personbiography_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonDateOfBirth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', django_date_extensions.fields.ApproximateDateField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_persondateofbirth_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('sources', models.ManyToManyField(related_name='person_persondateofbirth_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonDateOfDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', django_date_extensions.fields.ApproximateDateField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_persondateofdeath_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('sources', models.ManyToManyField(related_name='person_persondateofdeath_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonDeceased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.NullBooleanField(default=None)),
                ('accesspoints', models.ManyToManyField(related_name='person_persondeceased_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('sources', models.ManyToManyField(related_name='person_persondeceased_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personexternallink_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('sources', models.ManyToManyField(related_name='person_personexternallink_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_persongender_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('sources', models.ManyToManyField(related_name='person_persongender_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personnotes_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('sources', models.ManyToManyField(related_name='person_personnotes_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
