# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_personbiography_persondateofbirth_persondateofdeath_persondeceased_personexternallink_persongender_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondeceased',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
