# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_auto_20180727_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
