# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-13 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_person_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personbiography',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='personbiography',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='personbiography',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='persondateofbirth',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='persondateofbirth',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='persondateofbirth',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='persondateofdeath',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='persondateofdeath',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='persondateofdeath',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='persondeceased',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='persondeceased',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='persondeceased',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='personexternallink',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='personexternallink',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='personexternallink',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='persongender',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='persongender',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='persongender',
            name='sources',
        ),
        migrations.DeleteModel(
            name='PersonBiography',
        ),
        migrations.DeleteModel(
            name='PersonDateOfBirth',
        ),
        migrations.DeleteModel(
            name='PersonDateOfDeath',
        ),
        migrations.DeleteModel(
            name='PersonDeceased',
        ),
        migrations.DeleteModel(
            name='PersonExternalLink',
        ),
        migrations.DeleteModel(
            name='PersonGender',
        ),
    ]
