# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-11 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields
import sfm_pc.utils


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0037_source_metadata'),
        ('person', '0013_person_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, sfm_pc.utils.VersionsMixin),
        ),
        migrations.CreateModel(
            name='PersonExtraAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personextraaccount_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonExtra')),
                ('sources', models.ManyToManyField(related_name='person_personextraaccount_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonExtraAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personextraaccounttype_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonExtra')),
                ('sources', models.ManyToManyField(related_name='person_personextraaccounttype_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonExtraDateOfBirth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', django_date_extensions.fields.ApproximateDateField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personextradateofbirth_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonExtra')),
                ('sources', models.ManyToManyField(related_name='person_personextradateofbirth_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonExtraDateOfDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', django_date_extensions.fields.ApproximateDateField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personextradateofdeath_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonExtra')),
                ('sources', models.ManyToManyField(related_name='person_personextradateofdeath_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonExtraDeceased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.BooleanField(default=False)),
                ('accesspoints', models.ManyToManyField(related_name='person_personextradeceased_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonExtra')),
                ('sources', models.ManyToManyField(related_name='person_personextradeceased_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonExtraExternalLinkDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personextraexternallinkdescription_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonExtra')),
                ('sources', models.ManyToManyField(related_name='person_personextraexternallinkdescription_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonExtraGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personextragender_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonExtra')),
                ('sources', models.ManyToManyField(related_name='person_personextragender_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonExtraMediaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personextramediadescription_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonExtra')),
                ('sources', models.ManyToManyField(related_name='person_personextramediadescription_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonExtraNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('accesspoints', models.ManyToManyField(related_name='person_personextranotes_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonExtra')),
                ('sources', models.ManyToManyField(related_name='person_personextranotes_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonExtraPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('accesspoints', models.ManyToManyField(related_name='person_personextraperson_related', to='source.AccessPoint')),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonExtra')),
                ('sources', models.ManyToManyField(related_name='person_personextraperson_related', to='source.Source')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='personbiography',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='personbiography',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='personbiography',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='persondateofbirth',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='persondateofbirth',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='persondateofbirth',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='persondateofdeath',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='persondateofdeath',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='persondateofdeath',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='persondeceased',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='persondeceased',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='persondeceased',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='personexternallink',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='personexternallink',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='personexternallink',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='persongender',
            name='accesspoints',
        ),
        migrations.RemoveField(
            model_name='persongender',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='persongender',
            name='sources',
        ),
        migrations.DeleteModel(
            name='PersonBiography',
        ),
        migrations.DeleteModel(
            name='PersonDateOfBirth',
        ),
        migrations.DeleteModel(
            name='PersonDateOfDeath',
        ),
        migrations.DeleteModel(
            name='PersonDeceased',
        ),
        migrations.DeleteModel(
            name='PersonExternalLink',
        ),
        migrations.DeleteModel(
            name='PersonGender',
        ),
    ]
