# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0032_remove_source_id'),
        ('membershipperson', '0003_auto_20160810_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippersonendcontext',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersonendcontext_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='membershippersonfirstciteddate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersonfirstciteddate_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='membershippersonlastciteddate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersonlastciteddate_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='membershippersonmember',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersonmember_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='membershippersonorganization',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersonorganization_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='membershippersonrank',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersonrank_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='membershippersonrealend',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersonrealend_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='membershippersonrealstart',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersonrealstart_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='membershippersonrole',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersonrole_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='membershippersonstartcontext',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersonstartcontext_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='membershippersontitle',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershipperson_membershippersontitle_related', to='source.AccessPoint'),
        ),
    ]
