# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-13 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipperson', '0004_auto_20180706_1825'),
    ]

    operations = [
        migrations.RunSQL('''
            DROP MATERIALIZED VIEW IF EXISTS membershipperson
        '''),
        migrations.RunSQL('''
            DROP MATERIALIZED VIEW IF EXISTS membershipperson_sources
        '''),
    ]
