# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('membershipperson', '0005_auto_20180813_2103'),
    ]

    database_operations = [
        migrations.AlterField(
            model_name='membershippersonendcontext',
            name='value',
            field=models.ForeignKey('Context', db_constraint=False, db_index=True, on_delete=django.db.models.deletion.CASCADE)
        ),
        migrations.AlterField(
            model_name='membershippersonstartcontext',
            name='value',
            field=models.ForeignKey('Context', db_constraint=False, db_index=True, on_delete=django.db.models.deletion.CASCADE)
        ),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='membershippersonendcontext',
            name='value',
            field=models.IntegerField(db_index=True, null=False)
        ),
        migrations.RenameField(
            model_name='membershippersonendcontext',
            old_name='value',
            new_name='value_id'
        ),
        migrations.AlterField(
            model_name='membershippersonstartcontext',
            name='value',
            field=models.IntegerField(db_index=True, null=False)
        ),
        migrations.RenameField(
            model_name='membershippersonstartcontext',
            old_name='value',
            new_name='value_id'
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        ),
    ]
