# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipperson', '0005_auto_20180813_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippersonendcontext',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='membershippersonstartcontext',
            name='value',
            field=models.TextField(),
        ),
    ]
