# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-13 21:07
from __future__ import unicode_literals

import os

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipperson', '0006_auto_20180813_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippersonendcontext',
            name='value',
            field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name='membershippersonstartcontext',
            name='value',
            field=models.TextField(null=True)
        ),
    ]
