# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-13 21:07
from __future__ import unicode_literals

import os

from django.db import migrations, connection
from django.conf import settings


def remake_views(apps, schema_editor):

    sql_folder_path = os.path.join(settings.BASE_DIR, 'sfm_pc/management/commands/sql')
    view_paths = [
        os.path.join(sql_folder_path, 'membershipperson_view.sql'),
        os.path.join(sql_folder_path, 'membershipperson_sources_view.sql'),
    ]

    for view_path in view_paths:
        with open(view_path) as sql:
            with connection.cursor() as curs:
                curs.execute(sql.read())


class Migration(migrations.Migration):

    dependencies = [
        ('membershipperson', '0007_auto_20180813_2107'),
    ]

    operations = [
        migrations.RunSQL('''
            UPDATE membershipperson_membershippersonstartcontext SET
              value = s.value
            FROM (
              SELECT id, value FROM membershipperson_context
            ) AS s
            WHERE membershipperson_membershippersonstartcontext.value_id = s.id
        '''),
        migrations.RunSQL('''
            UPDATE membershipperson_membershippersonendcontext SET
              value = s.value
            FROM (
              SELECT id, value FROM membershipperson_context
            ) AS s
            WHERE membershipperson_membershippersonendcontext.value_id = s.id
        '''),
        migrations.RunPython(remake_views),
    ]
