# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0003_auto_20160628_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationtype',
            name='object_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='violation.Violation'),
        ),
    ]
