# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0004_auto_20160629_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationadminlevel1',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationadminlevel2',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationdescription',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationenddate',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationgeoname',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationgeonameid',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationlocation',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationlocationdescription',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationperpetrator',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationperpetratororganization',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationstartdate',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
    ]
