# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0016_auto_20160811_1711'),
        ('violation', '0006_auto_20160810_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ViolationPerpetratorClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('object_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='violation.Violation')),
                ('sources', models.ManyToManyField(related_name='violation_violationperpetratorclassification_related', to='source.Source')),
                ('value', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='violation.Classification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
