# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0007_classification_violationperpetratorclassification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classification',
            new_name='PerpetratorClassification',
        ),
    ]
