# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-05 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_auto_20160826_2057'),
        ('violation', '0010_auto_20161107_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationFirstAllegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', django_date_extensions.fields.ApproximateDateField(blank=True, default=None, null=True)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violation.Violation')),
                ('sources', models.ManyToManyField(related_name='violation_violationfirstallegation_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationLastUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', django_date_extensions.fields.ApproximateDateField(blank=True, default=None, null=True)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violation.Violation')),
                ('sources', models.ManyToManyField(related_name='violation_violationlastupdate_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violation.Violation')),
                ('sources', models.ManyToManyField(related_name='violation_violationstatus_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
