# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-15 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_auto_20160826_2057'),
        ('violation', '0012_violationsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationLocationId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violation.Violation')),
                ('sources', models.ManyToManyField(related_name='violation_violationlocationid_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationLocationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violation.Violation')),
                ('sources', models.ManyToManyField(related_name='violation_violationlocationname_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='violationsite',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='violationsite',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='violationsite',
            name='value',
        ),
        migrations.DeleteModel(
            name='ViolationSite',
        ),
    ]
