# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0032_remove_source_id'),
        ('violation', '0013_auto_20170915_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationadminlevel1',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationadminlevel1_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationadminlevel2',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationadminlevel2_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationdescription',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationdescription_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationdivisionid',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationdivisionid_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationenddate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationenddate_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationfirstallegation',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationfirstallegation_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationlastupdate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationlastupdate_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationlocation',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationlocation_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationlocationdescription',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationlocationdescription_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationlocationid',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationlocationid_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationlocationname',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationlocationname_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationosmid',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationosmid_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationosmname',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationosmname_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationperpetrator',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationperpetrator_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationperpetratorclassification',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationperpetratorclassification_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationperpetratororganization',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationperpetratororganization_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationstartdate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationstartdate_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationstatus',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationstatus_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='violationtype',
            name='accesspoints',
            field=models.ManyToManyField(related_name='violation_violationtype_related', to='source.AccessPoint'),
        ),
        migrations.AlterField(
            model_name='violationlocationdescription',
            name='sources',
            field=models.ManyToManyField(related_name='violation_violationlocationdescription_related', to='source.Source'),
        ),
    ]
