# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-21 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0014_auto_20180706_1825'),
    ]

    operations = [
        migrations.RunSQL('''
            DROP MATERIALIZED VIEW IF EXISTS violation
        '''),
        migrations.RunSQL('''
            DROP MATERIALIZED VIEW IF EXISTS violation_all_export
        '''),
        migrations.RunSQL('''
            DROP MATERIALIZED VIEW IF EXISTS violation_sources
        '''),
    ]
