# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0016_auto_20180821_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationperpetratorclassification',
            name='value',
            field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name='violationtype',
            name='value',
            field=models.TextField(null=True)
        ),
    ]
