# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-21 14:57
from __future__ import unicode_literals

import os

from django.db import migrations, connection
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0017_auto_20180821_1452'),
    ]

    operations = [
        migrations.RunSQL('''
            UPDATE violation_violationperpetratorclassification SET
              value=s.value
            FROM (
              SELECT id, value FROM violation_perpetratorclassification
            ) AS s
            WHERE violation_violationperpetratorclassification.value_id = s.id
        '''),
        migrations.RunSQL('''
            UPDATE violation_violationtype SET
              value=s.value
            FROM (
              SELECT id, code AS value FROM violation_type
            ) AS s
            WHERE violation_violationtype.value_id = s.id
        '''),
    ]
