# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0022_auto_20181227_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerpetratorClassification',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.RemoveField(
            model_name='violationperpetratorclassification',
            name='value_id',
        ),
        migrations.RemoveField(
            model_name='violationtype',
            name='value_id',
        ),
        migrations.AlterField(
            model_name='violationperpetratorclassification',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
