# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-13 21:09
from __future__ import unicode_literals

import complex_fields.base_models
from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_organization_uuid'),
        ('source', '0017_auto_20160826_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, complex_fields.base_models.BaseModel),
        ),
        migrations.CreateModel(
            name='MembershipOrganizationFirstCitedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', django_date_extensions.fields.ApproximateDateField()),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershiporganization.MembershipOrganization')),
                ('sources', models.ManyToManyField(related_name='membershiporganization_membershiporganizationfirstciteddate_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipOrganizationLastCitedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', django_date_extensions.fields.ApproximateDateField()),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershiporganization.MembershipOrganization')),
                ('sources', models.ManyToManyField(related_name='membershiporganization_membershiporganizationlastciteddate_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipOrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershiporganization.MembershipOrganization')),
                ('sources', models.ManyToManyField(related_name='membershiporganization_membershiporganizationmember_related', to='source.Source')),
                ('value', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipOrganizationOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershiporganization.MembershipOrganization')),
                ('sources', models.ManyToManyField(related_name='membershiporganization_membershiporganizationorganization_related', to='source.Source')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
