# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-14 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membershiporganization', '0002_auto_20161214_1451'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membershiporganizationfirstciteddate',
            table='membershiporganization_fcd',
        ),
        migrations.AlterModelTable(
            name='membershiporganizationlastciteddate',
            table='membershiporganization_lcd',
        ),
    ]
