# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-07 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_auto_20160826_2057'),
        ('membershiporganization', '0005_membershiporganizationopenended_membershiporganizationrealstart'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipOrganizationRealEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, null=True)),
                ('confidence', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1)),
                ('value', models.NullBooleanField(default=None)),
                ('object_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershiporganization.MembershipOrganization')),
                ('sources', models.ManyToManyField(related_name='membershiporganization_membershiporganizationrealend_related', to='source.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='membershiporganizationopenended',
            name='object_ref',
        ),
        migrations.RemoveField(
            model_name='membershiporganizationopenended',
            name='sources',
        ),
        migrations.DeleteModel(
            name='MembershipOrganizationOpenEnded',
        ),
    ]
