# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import sfm_pc.fields


class Migration(migrations.Migration):

    dependencies = [
        ('membershiporganization', '0008_rename_realend_to_openended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiporganizationfirstciteddate',
            name='value',
            field=sfm_pc.fields.I10nApproximateDateField(),
        ),
        migrations.AlterField(
            model_name='membershiporganizationlastciteddate',
            name='value',
            field=sfm_pc.fields.I10nApproximateDateField(),
        ),
        migrations.AlterField(
            model_name='membershiporganizationopenended',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershiporganization_membershiporganizationopenended_related', to='source.AccessPoint'),
        ),
        migrations.AlterField(
            model_name='membershiporganizationopenended',
            name='sources',
            field=models.ManyToManyField(related_name='membershiporganization_membershiporganizationopenended_related', to='source.Source'),
        ),
        migrations.AlterModelTable(
            name='membershiporganizationopenended',
            table=None,
        ),
    ]
