# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-21 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershiporganization', '0008_rename_realend_to_openended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiporganizationopenended',
            name='accesspoints',
            field=models.ManyToManyField(related_name='membershiporganization_membershiporganizationopenended_related', to='source.AccessPoint'),
        ),
        migrations.AlterField(
            model_name='membershiporganizationopenended',
            name='sources',
            field=models.ManyToManyField(related_name='membershiporganization_membershiporganizationopenended_related', to='source.Source'),
        ),
        migrations.AlterModelTable(
            name='membershiporganizationopenended',
            table=None,
        ),
    ]
