# Generated by Django 3.1 on 2022-04-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershiporganization', '0010_auto_20220411_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiporganizationrealstart',
            name='value',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
