# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0003_auto_20160810_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionchild',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='compositionclassification',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='compositionenddate',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='compositionparent',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='compositionstartdate',
            name='confidence',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1, max_length=1),
        ),
    ]
