# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-05 20:06
from __future__ import unicode_literals

from django.db import migrations, models


def map_new_type(apps, schema_editor):

    CompositionOpenEnded = apps.get_model("composition", "CompositionOpenEnded")
    db_alias = schema_editor.connection.alias

    compositions = CompositionOpenEnded.objects.using(db_alias).all()

    for comp in compositions:

        if comp.value == True:

            comp.new_value = 'Y'

        elif comp.value == False:

            comp.new_value = 'E'

        else:

            comp.new_value = 'N'

        comp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0005_compositionopenended'),
    ]

    operations = [
        migrations.RunSQL(
            'SET CONSTRAINTS ALL IMMEDIATE',
            reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            'DROP MATERIALIZED VIEW IF EXISTS composition',
            reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='compositionopenended',
            name='new_value',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('E', 'Exact')], default='N', max_length=1),
        ),
        migrations.RunPython(map_new_type),
        migrations.RemoveField(
            model_name='compositionopenended',
            name='value',
        ),
        migrations.RenameField(
            model_name='compositionopenended',
            old_name='new_value',
            new_name='value'
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'
        )
    ]
