# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0031_auto_20180705_1536'),
        ('composition', '0007_compositionrealstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionchild',
            name='accesspoints',
            field=models.ManyToManyField(related_name='composition_compositionchild_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='compositionclassification',
            name='accesspoints',
            field=models.ManyToManyField(related_name='composition_compositionclassification_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='compositionenddate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='composition_compositionenddate_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='compositionopenended',
            name='accesspoints',
            field=models.ManyToManyField(related_name='composition_compositionopenended_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='compositionparent',
            name='accesspoints',
            field=models.ManyToManyField(related_name='composition_compositionparent_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='compositionrealstart',
            name='accesspoints',
            field=models.ManyToManyField(related_name='composition_compositionrealstart_related', to='source.AccessPoint'),
        ),
        migrations.AddField(
            model_name='compositionstartdate',
            name='accesspoints',
            field=models.ManyToManyField(related_name='composition_compositionstartdate_related', to='source.AccessPoint'),
        ),
    ]
