# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-24 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0010_auto_20180824_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionclassification',
            name='value',
            field=models.TextField(null=True)
        )
    ]
