# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0012_auto_20180824_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.RemoveField(
            model_name='compositionclassification',
            name='value_id',
        ),
        migrations.AlterField(
            model_name='compositionclassification',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
