# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_auto_20160615_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='archive_url',
            field=models.URLField(null=True),
        ),
    ]
