# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_auto_20160728_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(null=True),
        ),
    ]
