# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_auto_20160729_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
