# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0013_auto_20160805_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='archive_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
