# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0015_source_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 11, 17, 11, 0, 258907, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 11, 17, 11, 13, 266867, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
