# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0016_auto_20160811_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='accessed_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='page_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
