# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_auto_20160826_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='publication_country',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='publication',
            field=models.TextField(null=True),
        ),
        migrations.RunSQL(
            [('''
                UPDATE source_source SET
                  publication = s.title,
                  publication_country = s.country
                FROM (
                  SELECT
                    title,
                    id,
                    country
                  FROM source_publication
                ) AS s
                WHERE source_source.publication_id = s.id
            ''')]
        ),
        migrations.AlterField(
            model_name='source',
            name='publication',
            field=models.TextField(null=False),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
