# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-01 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0018_auto_20180530_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='publication',
            field=models.TextField(null=True),
        ),
    ]
