# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-01 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0019_auto_20180601_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='page_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
