# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0020_auto_20180601_1832'),
        ('violation', '0013_auto_20170915_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
