# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-04 16:10
from __future__ import unicode_literals

import uuid

from django.db import migrations


def get_uuid(apps, schema_editor):
    Source = apps.get_model('source', 'Source')
    for row in Source.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0021_auto_20180604_1605'),
    ]

    operations = [
        migrations.RunPython(get_uuid, reverse_code=migrations.RunPython.noop)
    ]
