# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-04 16:10
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0022_auto_20180604_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='id',
        ),
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True)
        )
    ]
