# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import source.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source', '0023_auto_20180604_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('page_number', models.CharField(blank=True, max_length=255, null=True)),
                ('accessed_on', models.DateField(null=True)),
                ('archive_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(source.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='source',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='source.Source',
                                    to_field='uuid'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(source.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
