# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 20:41
from __future__ import unicode_literals

import uuid

from django.db import migrations

def save_accesspoints(apps, schema_editor):
    AccessPoint = apps.get_model('source', 'AccessPoint')
    Source = apps.get_model('source', 'Source')

    for source in Source.objects.all():
        accesspoint = AccessPoint(source=source,
                                  user=source.user,
                                  accessed_on=source.accessed_on,
                                  archive_url=source.archive_url,
                                  page_number=source.page_number)
        accesspoint.save()


def remove_accesspoints(apps, schema_editor):
    AccessPoint = apps.get_model('source', 'AccessPoint')

    for accesspoint in AccessPoint.objects.all():
        accesspoint.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0024_auto_20180606_2037'),
    ]

    operations = [
        migrations.RunPython(save_accesspoints, reverse_code=remove_accesspoints)
    ]
