# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 20:41
from __future__ import unicode_literals

import uuid

from django.db import migrations

def save_accesspoints(apps, schema_editor):
    AccessPoint = apps.get_model('source', 'AccessPoint')
    Source = apps.get_model('source', 'Source')

    for source in Source.objects.all():
        accesspoint = AccessPoint(source=source,
                                  user=source.user,
                                  accessed_on=source.accessed_on,
                                  archive_url=source.archive_url,
                                  page_number=source.page_number)
        accesspoint.save()


def remove_accesspoints(apps, schema_editor):
    AccessPoint = apps.get_model('source', 'AccessPoint')

    for accesspoint in AccessPoint.objects.all():
        accesspoint.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0024_auto_20180606_2037'),
        ('area', '0009_auto_20161230_1629'),
        ('association', '0005_auto_20170905_2006'),
        ('composition', '0007_compositionrealstart'),
        ('emplacement', '0007_auto_20170908_1835'),
        ('membershiporganization', '0006_auto_20170907_1853'),
        ('membershipperson', '0003_auto_20160810_2017'),
        ('organization', '0011_organizationheadquarters'),
        ('violation', '0013_auto_20170915_1614'),
        ('person', '0006_person_uuid'),
    ]

    operations = [
        migrations.RunPython(save_accesspoints, reverse_code=remove_accesspoints)
    ]
