# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0024_auto_20180606_2037'),
    ]

    operations = [
        migrations.RunSQL('''
            INSERT INTO source_accesspoint (
              source_id,
              user_id,
              accessed_on,
              archive_url,
              page_number
            )
            SELECT
              uuid AS source_id,
              user_id,
              accessed_on,
              archive_url,
              page_number
            FROM source_source
        ''')
    ]
