# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0025_auto_20180606_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='accessed_on',
        ),
        migrations.RemoveField(
            model_name='source',
            name='archive_url',
        ),
        migrations.RemoveField(
            model_name='source',
            name='page_number',
        ),
    ]
