# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-08 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0026_auto_20180606_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='accessed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
