# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0028_auto_20180705_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
