# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0035_auto_20180820_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='accessed_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='archive_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
