# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-11 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0036_auto_20190131_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspoint',
            old_name='page_number',
            new_name='trigger',
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='author',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='created_on',
            field=django_date_extensions.fields.ApproximateDateField(null=True, verbose_name='creation date'),
        ),
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='uploaded_on',
            field=django_date_extensions.fields.ApproximateDateField(null=True, verbose_name='upload date'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='accessed_on',
            field=models.DateField(null=True, verbose_name='access date'),
        ),
        migrations.AlterField(
            model_name='source',
            name='published_on',
            field=django_date_extensions.fields.ApproximateDateField(verbose_name='publication date'),
        ),
    ]
