# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 16:02
from __future__ import unicode_literals

from django.db import migrations
import source.fields


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0037_source_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='publication',
            field=source.fields.TextField(null=True, verbose_name='publication'),
        ),
        migrations.AlterField(
            model_name='source',
            name='publication_country',
            field=source.fields.CharField(max_length=1000, null=True, verbose_name='publication country'),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=source.fields.TextField(verbose_name='title'),
        ),
    ]
