# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-18 20:21
from __future__ import unicode_literals

from django.db import migrations
import source.fields


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0039_length_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='title',
            field=source.fields.TextField(verbose_name='publication title'),
        ),
    ]
